### ISSUE TITLE
[P4G] Apparent incompatibility with Persona 4 Golden

### ISSUE THREAD

**Issue by AFriendlyIrin** [Sewer56/p5rpc.modloader#26] opened 2023-11-19 17:15 UTC
Attempting to launch P4G via Reloaded II with Persona Essentials enabled results in the following (very weird) issue:
![image](https://github.com/Sewer56/p5rpc.modloader/assets/77584000/2ac0c58c-f934-41e3-8383-a7c3e7db9247)

Reloaded II and Persona Essentials are the latest versions, and all prerequisites were successfully installed.

OS is Windows 10, build 19045.3693

**Comment by Sewer56** [comment] 2023-11-19 20:51
Can you get a screen capture of this, including game folder?
Windows version would be handy too.

Usually this kind of error is a very deep low level error that could only be resolved by porting some low level mods away from C#; however, in practice it's usually caused by another low level error elsewhere.

**Comment by AFriendlyIrin** [comment] 2023-11-19 20:57
Here's the mod folder ("P4G Mods" is stored on my desktop):
![image](https://github.com/Sewer56/p5rpc.modloader/assets/77584000/9470faf0-1c59-4598-ae2d-aa46b9ba6e2e)

The game data itself is stored on a flash drive. I don't know if that's causing the issue, but it doesn't cause any errors with other mods.

**Comment by Sewer56** [comment] 2023-11-19 21:27
Game location shouldn't hopefully cause any issues. Feel free to move it to main storage to test though.

I assume the game is 64-bit version (32-bit/old port is unsupported with the mods you're running).

Hard to isolate issues like this.

I'd personally try vanilla'ing the game as much as possible for the time being. i.e.
- Disabling mods one by one (just strip it down to Essentials).
- Killing any external overlays/injection systems (e.g. RTSS, which ships with MSI AfterBurner; Nahimic audio driver OSD)

etc.

If it comes to worst, generate a crash dump. Normally my code should give you one, but I guess that's not being triggered.

I don't remember if P4G generates Crash Dumps, but if it does, they should be in `%APPDATA%\SEGA\P4G\Steam\xxxxx\db\reports ` if they do, otherwise [follow this guide](https://helpx.adobe.com/uk/xd/kb/how-to-generate-crash-dump-on-windows-machine.html) up to (and including Step 4), and you should be able to see a `.dmp` file inside `%LOCALAPPDATA%\CrashDumps`

**Comment by AFriendlyIrin** [comment] 2023-11-19 21:54
I have a crash dump, but I can't upload it here, as it's bigger than the 25MB limit.

**Comment by Sewer56** [comment] 2023-11-19 21:58
Compress it and upload it wherever you can

**Comment by AFriendlyIrin** [comment] 2023-11-19 22:08
Here: https://mega.nz/file/YSdW3L7T#QZjKNUy4zhv2Akg9L9F8hD-L7KSOVxGwo79_X4V1MXg

**Comment by Sewer56** [comment] 2023-11-19 22:50
> I assume the game is 64-bit version (32-bit/old port is unsupported with the mods you're running).
 
According to your crash dump you are running the 32-bit version of Persona 4 Golden with mods meant for the 64-bit version.

**Comment by Sewer56** [comment] 2023-11-19 22:55
In other words, no issue there. Use legacy `p4gpc.modloader` from TGE and mods for the 32-bit version if you want to mod the old version.

**Closed by Sewer56** 2023-11-19 22:55 UTC
